version: 2.1

jobs: # a basic unit of work in a run
  build:
    macos:
      xcode: 13.1.0 # indicate our selected version of Xcode
    steps:
      - checkout
      - run:
          # build our application
          name: Build Application
          command: swift build

  test: # your job name
    macos:
      xcode: 13.1.0 # indicate our selected version of Xcode
    steps: # a series of commands to run
      - checkout # pull down code from your version control system.
      - run:
          name: Run Unit Tests
          command: swift test

workflows:
  version: 2
  test_build:
    jobs:
      - build
      - test:
        requires: build
